:toc:
:toc-title: Índice
:toc-placement!:

= ThreescaleApicastLatencyHigh

toc::[]

== Descrição

* Este alerta será acionado se a latência do `apicast-staging`/`apicast-production` **p99** for maior que um determinado limite
* A métrica de latência inclui o tempo que a solicitação passou no apicast mais o tempo que o upstream levou para responder

== Solução de problemas

* Verifique se os pods `apicast-staging`/`apicast-production` podem não ser capazes de lidar com o tráfego de entrada devido ao alto uso da CPU
- Talvez seja necessário considerar o dimensionamento horizontal do deploy do `apicast-staging`/`apicast-production`
- Talvez seja necessário considerar aumentar as solicitações/limites de recursos do deploy do `apicast-staging`/`apicast-production`
* Verifique se a resposta upstream está demorando muito
* Verifique se o tráfego atual é normal com base nos dados históricos. Uma mudança inesperada no padrão de tráfego pode ser legítima e exigirá ampliação, mas também pode ser devido a um tráfego anormal ou malicioso

== Verificação

* O alerta deve desaparecer quando a latência do `apicast-staging`/`apicast-production` **p99** estiver abaixo do limite
