:toc:
:toc-title: Índice
:toc-placement!:

= ThreescaleApicastRequestTime

toc::[]

== Descrição

* Este alerta será acionado se houver um grande número de solicitações `apicast-staging`/`apicast-production` sendo processadas lentamente (abaixo de um determinado limite)
* A métrica de tempo de solicitação inclui apenas o tempo que a solicitação passou no apicast

== Solução de problemas

* Verifique se os pods `apicast-staging`/`apicast-production` podem não ser capazes de lidar com o tráfego de entrada devido ao alto uso da CPU
- Talvez seja necessário considerar o dimensionamento horizontal do deploy do `apicast-staging`/`apicast-production`
- Talvez seja necessário considerar aumentar as solicitações/limites de recursos do deploy do `apicast-staging`/`apicast-production`
* Verifique se o tráfego atual é normal com base nos dados históricos. Uma mudança inesperada no padrão de tráfego pode ser legítima e exigirá ampliação, mas também pode ser devido a um tráfego anormal ou malicioso

== Verificação

* O alerta deve desaparecer quando o número de solicitações lentas de `apicast-staging`/`apicast-production` estiver abaixo do limite
