:toc:
:toc-title: Índice
:toc-placement!:

= ThreescaleBackendWorkerJobsCountRunningHigh

toc::[]

== Descrição

* Este alerta será acionado se o número de _workers_ `backend-worker` for maior que um determinado limite

== Solução de problemas

* Verifique se os pods `backend-worker` podem estar falhando e os _jobs_ não estão sendo consumidos do redis do backend
* Verifique se os pods `backend-worker` podem não estar consumindo _jobs_ na taxa de transferência necessária:
- Talvez seja necessário considerar o dimensionamento horizontal do _deploy_ do `backend-worker`
- Você pode precisar considerar aumentar as solicitações/limites de recursos do _deploy_ do `backend-worker`
* Verifique se o tráfego atual no `backend-listener` é normal com base nos dados históricos. Uma mudança inesperada no padrão de tráfego pode ser legítima e exigirá ampliação, mas também pode ser devido a um tráfego anormal ou mal-intencionado. Seja qual for o motivo, o aumento do tráfego no `backend-listener` gera mais _jobs_ para o `backend-worker` processar a partir do redis do backend
* Verifique se o redis do backend está com problemas

== Verificação

* O alerta deve desaparecer quando o número de _jobs_ de `backend-worker` estiver abaixo do limite
