:toc:
:toc-title: Índice
:toc-placement!:

= ThreescaleBackendListener5XXRequestsHigh

toc::[]

== Descrição

* Este alerta será acionado se o número de solicitações HTTP 5XX do `backend-listener` for maior que um determinado limite

== Solução de problemas

* Verifique se os pods `backend-listener` podem estar falhando
* Verifique se os pods `backend-listener` podem não ser capazes de lidar com o tráfego de entrada devido ao alto uso da CPU
- Pode ser necessário considerar o dimensionamento horizontal do deploy do `backend-listener`
- Você pode precisar considerar aumentar as solicitações/limites de recursos do deploy do `backend-listener`
* Verifique se o redis do backend está com problemas
* Verifique se o tráfego atual é normal com base nos dados históricos. Uma mudança inesperada no padrão de tráfego pode ser legítima e exigirá ampliação, mas também pode ser devido a um tráfego anormal ou malicioso

== Verification

* O alerta deve desaparecer quando o número de solicitações HTTP 5XX do `backend-listener` estiver abaixo do limite
