:toc:
:toc-title: Índice
:toc-placement!:

= ThreescalePrometheusJobDown

toc::[]

== Descrição

* Este alerta será acionado quando um _job_ do _prometheus_ estiver inativo, porque `ServiceMonitor`/`PodMonitor` pode ter problemas para conectar com o aplicativo `Service`/`Pods`
* Este alerta é importante porque se você tiver alertas baseados em métricas do aplicativo que não podem ser obtidos porque o trabalho do _prometheus_ associado está falhando, você perderá a visibilidade do aplicativo

== Solução de problemas

* Verifique se o aplicativo descartado (ou o endpoint de métricas do aplicativo) pode estar falhando e o conexão não pode ser feita
* Verifique se o `ServiceMonitor`/`PodMonitor` pode estar mal configurado apontando para rótulo, porta, caminho incorreto...
* Verifique se _prometheus_ está tendo algum problema, ou se _prometheus_ não recarregou sua configuração com um possível novo `ServiceMonitor`/`PodMonitor`

== Verificação

* O alerta deve desaparecer assim que o alvo do Prometheus começar a conectar com todos os pods
