:toc:
:toc-title: Índice
:toc-placement!:

= ThreescaleSystemApp5XXRequestsHigh

toc::[]

== Descrição

* Este alerta será acionado se o número de solicitações HTTP 5XX do `system-app` for maior que um determinado limite

== Solução de problemas

* Verifique se os pods `system-app` podem estar falhando
* Verifique se os pods `system-app` podem não ser capazes de lidar com o tráfego de entrada devido ao alto uso da CPU
- Pode ser necessário considerar o dimensionamento horizontal do _deploy_  do `system-app`
- Você pode precisar considerar aumentar as solicitações/limites de recursos do _deploy_  do `system-app`
* Verifique se o banco de dados mysql `system-mysql` (ou mesmo o redis `system-redis`) está com problemas
* Verifique se o tráfego atual é normal com base nos dados históricos. Uma mudança inesperada no padrão de tráfego pode ser legítima e exigirá ampliação, mas também pode ser devido a um tráfego anormal ou malicioso 7

== Verificação

* O alerta deve desaparecer quando o número de solicitações HTTP 5XX do `system-app` estiver abaixo do limite
